alias gti='git'
alias tmux='tmux -2'
alias less='less -R'
alias diff='colordiff'
alias dc='cd'
alias yams='find . -type f -name "*.yml*" | sed "s|\./||g" | egrep -v "(\.kitchen/|\[warning\]|\.molecule/)" | xargs yamllint -f parsable'
alias glog='git log --oneline --graph --color --all --decorate'
alias ll='ls -la --color=auto'
alias ls='ls --color=auto'
alias dazey_mount='sudo sshfs -o allow_other,default_permissions,IdentityFile=/home/mdazey/.ssh/id_rsa -p2020 mark@pi.dazeysolutions.com:/nfs /mnt/nfs.dazey/'
alias dazey_umount='sudo umount /mnt/nfs.dazey'
